namespace Spine
{
	public enum Property
	{
		Rotate,
		X,
		Y,
		ScaleX,
		ScaleY,
		ShearX,
		ShearY,
		Inherit,
		RGB,
		Alpha,
		RGB2,
		Attachment,
		Deform,
		Event,
		DrawOrder,
		IkConstraint,
		TransformConstraint,
		PathConstraintPosition,
		PathConstraintSpacing,
		PathConstraintMix,
		PhysicsConstraintInertia,
		PhysicsConstraintStrength,
		PhysicsConstraintDamping,
		PhysicsConstraintMass,
		PhysicsConstraintWind,
		PhysicsConstraintGravity,
		PhysicsConstraintMix,
		PhysicsConstraintReset,
		Sequence
	}
}
